import { mkdir, mkdtemp, rm, utimes, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { getPortabilityConfig } from "./config";
import { detectConflicts } from "./conflicts";
import { inspectPortabilityReadiness } from "./readiness";
import { inspectOneDriveLocal } from "./one-drive";
import { compareSnapshots, computeRootHash, createStableSnapshot, createVaultSnapshot } from "./snapshots";
import type { MachineIdentity, VaultSnapshot } from "./types";

const roots: string[] = []; const identity: MachineIdentity = { schemaVersion: 1, machineId: "11111111-1111-4111-8111-111111111111", displayName: "Tour", createdAt: "2026-07-22T12:00:00Z", rolePreference: "writer" };
async function fixture() { const root = await mkdtemp(path.join(os.tmpdir(), "tk-p6-snapshot-")); roots.push(root); const oneDrive = path.join(root, "OneDrive"); const vault = path.join(oneDrive, "vault"); await mkdir(path.join(vault, "01_BIBLIOTHEQUE"), { recursive: true }); await writeFile(path.join(vault, "INDEX.md"), "# Index\n"); await writeFile(path.join(vault, "01_BIBLIOTHEQUE", "note.md"), "# Note\n"); const env = { YOUTUBE_LIBRARY_PATH: vault, TUBEKNOWLEDGE_ONEDRIVE_ROOT: oneDrive, TUBEKNOWLEDGE_PORTABILITY_STATE_PATH: path.join(root, "state"), TUBEKNOWLEDGE_BACKUP_PATH: path.join(root, "backups"), TUBEKNOWLEDGE_STABILITY_WINDOW_SECONDS: "0" }; return { root, oneDrive, vault, env, config: getPortabilityConfig(env) }; }
afterEach(async () => { await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true }))); });

describe("snapshots, disponibilité et conflits", () => {
  it("produit un ordre/rootHash stable et exclut les métadonnées", async () => { const f = await fixture(); await mkdir(path.join(f.vault, ".tubeknowledge")); await writeFile(path.join(f.vault, ".tubeknowledge", "secret.md"), "secret"); const first = await createVaultSnapshot(f.vault, identity.machineId); const second = await createVaultSnapshot(f.vault, identity.machineId); expect(first.files.map((file) => file.path)).toEqual(["01_BIBLIOTHEQUE/note.md", "INDEX.md"]); expect(first.rootHash).toBe(second.rootHash); expect(computeRootHash([...first.files].reverse())).toBe(first.rootHash); });
  it("détecte ajout, suppression et hash modifié même avec mtime restauré", async () => { const f = await fixture(); const first = await createVaultSnapshot(f.vault, identity.machineId); const target = path.join(f.vault, "INDEX.md"); const date = new Date(first.files.find((file) => file.path === "INDEX.md")!.modifiedAt); await writeFile(target, "# Autre\n"); await utimes(target, date, date); const second = await createVaultSnapshot(f.vault, identity.machineId); expect(compareSnapshots(first, second)).toMatchObject({ stable: false, changedPaths: ["INDEX.md"] }); await writeFile(path.join(f.vault, "new.md"), "x"); const third = await createVaultSnapshot(f.vault, identity.machineId); expect(compareSnapshots(second, third).changedPaths).toContain("new.md"); await rm(path.join(f.vault, "new.md")); expect(compareSnapshots(third, await createVaultSnapshot(f.vault, identity.machineId)).changedPaths).toContain("new.md"); });
  it("applique la fenêtre double snapshot et la limite de fichiers", async () => { const f = await fixture(); await expect(createStableSnapshot(f.vault, identity.machineId, 0, { wait: async () => writeFile(path.join(f.vault, "INDEX.md"), "change") })).rejects.toThrow("VAULT_UNSTABLE"); await expect(createVaultSnapshot(f.vault, identity.machineId, { maxFiles: 1 })).rejects.toThrow("dépasse"); });
  it("distingue ready-local, racine non reconnue, vault absent et placeholder", async () => { const f = await fixture(); const ready = await inspectPortabilityReadiness(f.vault, f.config, identity, f.env); expect(ready).toMatchObject({ status: "ready-local", localState: "État local stable", cloudState: "Synchronisation cloud non vérifiée" }); const uncertain = await inspectPortabilityReadiness(f.vault, getPortabilityConfig({ ...f.env, TUBEKNOWLEDGE_ONEDRIVE_ROOT: path.join(f.root, "Other") }), identity, { ...f.env, TUBEKNOWLEDGE_ONEDRIVE_ROOT: path.join(f.root, "Other") }); expect(uncertain.status).toBe("sync-uncertain"); expect((await inspectPortabilityReadiness(path.join(f.root, "missing"), f.config, identity, f.env)).status).toBe("vault-missing"); await rm(path.join(f.vault, "INDEX.md")); expect((await inspectPortabilityReadiness(f.vault, f.config, identity, f.env)).status).toBe("offline-placeholder"); });
  it("détecte Offline/Unpinned avant toute lecture de placeholder", async () => { const f = await fixture(); const probe = await inspectOneDriveLocal(f.vault, f.config, f.env, async () => ({ offline: true, unpinned: true })); expect(probe).toMatchObject({ indexReadable: false, placeholderPaths: ["INDEX.md"] }); });
  it("bloque un placeholder secondaire avant son hash", async () => { const f = await fixture(); await expect(createVaultSnapshot(f.vault, identity.machineId, { attributeProbe: async (target) => ({ offline: target.endsWith("note.md"), unpinned: false }) })).rejects.toMatchObject({ code: "PLACEHOLDER_DETECTED" }); });
  it("détecte collision de casse, copie conflictuelle, placeholder et mismatch", async () => { const f = await fixture(); const snapshot: VaultSnapshot = { schemaVersion: 1, snapshotId: "22222222-2222-4222-8222-222222222222", createdAt: new Date().toISOString(), machineId: identity.machineId, fileCount: 3, totalBytes: 3, rootHash: "a".repeat(64), files: [{ path: "A.md", size: 1, sha256: "b".repeat(64), modifiedAt: new Date().toISOString() }, { path: "a.md", size: 1, sha256: "c".repeat(64), modifiedAt: new Date().toISOString() }, { path: "note conflicted copy.md", size: 1, sha256: "d".repeat(64), modifiedAt: new Date().toISOString() }] }; const conflicts = await detectConflicts(snapshot, f.config, { schemaVersion: 1, checkpointId: "33333333-3333-4333-8333-333333333333", rootHash: "e".repeat(64), machineId: identity.machineId, action: "backup", createdAt: new Date().toISOString() }, { placeholderPaths: ["offline.md"] }); expect(conflicts.map((item) => item.type)).toEqual(expect.arrayContaining(["case-collision", "onedrive-conflict-copy", "incomplete-placeholder", "checkpoint-mismatch"])); });
  it("compare au snapshot local précédent et traite l’expiration writer hors des conflits de connaissance", async () => { const f = await fixture(); const base = await createVaultSnapshot(f.vault, identity.machineId); await writeFile(path.join(f.vault, "INDEX.md"), "# Divergent\n"); await rm(path.join(f.vault, "01_BIBLIOTHEQUE", "note.md")); await writeFile(path.join(f.vault, "outside.md"), "# Divergent\n"); const current = await createVaultSnapshot(f.vault, identity.machineId); const conflicts = await detectConflicts(current, f.config, null, { baseSnapshot: base, writerAuthority: { schemaVersion: 1, authorityId: "44444444-4444-4444-8444-444444444444", machineId: identity.machineId, displayName: "Tour", grantedAt: "2026-01-01T00:00:00Z", expiresAt: "2026-01-01T00:01:00Z", checkpointId: "55555555-5555-4555-8555-555555555555", status: "active" }, now: new Date("2026-01-01T00:02:00Z") }); expect(conflicts.map((item) => item.type)).toEqual(expect.arrayContaining(["content-divergence", "deleted-vs-modified", "duplicate-suspected", "unexpected-system-change"])); expect(conflicts.map((item) => item.type)).not.toContain("stale-writer-authority"); });
});
