import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { createPortabilityBackup } from "./backup-builder";
import { createCheckpoint, readCheckpoint } from "./checkpoints";
import { getPortabilityConfig } from "./config";
import { acceptHandoff, prepareHandoff, readHandoff } from "./handoff";
import { ensureMachineIdentity } from "./machine-identity";
import { assertPortabilityWriteAllowed } from "./safety-gate";
import { createVaultSnapshot } from "./snapshots";
import { acquireWriterAuthority, assertWriterAuthority, readWriterAuthority, releaseWriterAuthority } from "./writer-authority";

const roots: string[] = [];
async function fixture() { const root = await mkdtemp(path.join(os.tmpdir(), "tk-p6-writer-")); roots.push(root); const oneDrive = path.join(root, "OneDrive"); const vault = path.join(oneDrive, "vault"); await mkdir(path.join(vault, "01_BIBLIOTHEQUE"), { recursive: true }); await writeFile(path.join(vault, "INDEX.md"), "# Index\n"); await writeFile(path.join(vault, "01_BIBLIOTHEQUE", "note.md"), "# Note\n"); const envA = { YOUTUBE_LIBRARY_PATH: vault, TUBEKNOWLEDGE_ONEDRIVE_ROOT: oneDrive, TUBEKNOWLEDGE_PORTABILITY_STATE_PATH: path.join(root, "state-a"), TUBEKNOWLEDGE_BACKUP_PATH: path.join(root, "backup-a"), TUBEKNOWLEDGE_STABILITY_WINDOW_SECONDS: "0", TUBEKNOWLEDGE_MACHINE_NAME: "Tour", TUBEKNOWLEDGE_MACHINE_ROLE: "writer" }; const envB = { ...envA, TUBEKNOWLEDGE_PORTABILITY_STATE_PATH: path.join(root, "state-b"), TUBEKNOWLEDGE_BACKUP_PATH: path.join(root, "backup-b"), TUBEKNOWLEDGE_MACHINE_NAME: "Portable", TUBEKNOWLEDGE_MACHINE_ROLE: "reader" }; const configA = getPortabilityConfig(envA); const configB = getPortabilityConfig(envB); const a = await ensureMachineIdentity(configA, { machineId: "11111111-1111-4111-8111-111111111111" }); const b = await ensureMachineIdentity(configB, { machineId: "22222222-2222-4222-8222-222222222222" }); const snapshot = await createVaultSnapshot(vault, a.machineId); const checkpoint = await createCheckpoint(vault, snapshot, "backup", { checkpointId: "33333333-3333-4333-8333-333333333333" }); const backup = await createPortabilityBackup(vault, configA, a); return { vault, envA, envB, configA, configB, a, b, snapshot, checkpoint, backup }; }
afterEach(async () => { await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true }))); });

describe("checkpoint, writer, handoff et safety gate", () => {
  it("écrit un checkpoint immuable", async () => { const f = await fixture(); expect((await readCheckpoint(f.vault, f.checkpoint.checkpointId)).rootHash).toBe(f.snapshot.rootHash); await expect(createCheckpoint(f.vault, f.snapshot, "backup", { checkpointId: f.checkpoint.checkpointId })).rejects.toThrow(); });
  it("n’accorde jamais writer implicitement et exige backup pour reprise forcée", async () => { const f = await fixture(); await expect(assertWriterAuthority(f.vault, f.a)).rejects.toMatchObject({ code: "WRITER_AUTHORITY_REQUIRED" }); await expect(acquireWriterAuthority(f.vault, f.a, f.checkpoint, 30, { force: true })).rejects.toMatchObject({ code: "BACKUP_REQUIRED" }); const authority = await acquireWriterAuthority(f.vault, f.a, f.checkpoint, 30, { force: true, verifiedBackupId: f.backup.backupId, confirmationText: "REPRENDRE" }); expect(authority.machineId).toBe(f.a.machineId); await expect(assertWriterAuthority(f.vault, f.b)).rejects.toMatchObject({ code: "WRITER_ACTIVE_ELSEWHERE" }); await releaseWriterAuthority(f.vault, f.a); expect((await readWriterAuthority(f.vault))?.status).toBe("released"); await expect(acquireWriterAuthority(f.vault, f.b, f.checkpoint, 30)).rejects.toMatchObject({ code: "HANDOFF_REQUIRED" }); });
  it("traite une autorité expirée comme inactive", async () => { const f = await fixture(); await acquireWriterAuthority(f.vault, f.a, f.checkpoint, 1, { now: new Date("2026-01-01T00:00:00Z"), force: true, verifiedBackupId: f.backup.backupId, confirmationText: "REPRENDRE" }); await expect(assertWriterAuthority(f.vault, f.a, new Date("2026-01-01T00:02:00Z"))).rejects.toMatchObject({ code: "WRITER_EXPIRED_LOCAL" }); });
  it("prépare, expire/refuse le replay et accepte un handoff inverse explicite", async () => { const f = await fixture(); await acquireWriterAuthority(f.vault, f.a, f.checkpoint, 30, { force: true, verifiedBackupId: f.backup.backupId, confirmationText: "REPRENDRE" }); const handoff = await prepareHandoff(f.vault, f.a, f.snapshot, f.checkpoint, f.backup, { now: new Date("2026-07-22T12:00:00Z") }); expect((await readHandoff(f.vault, handoff.handoffId)).status).toBe("prepared"); const bSnapshot = await createVaultSnapshot(f.vault, f.b.machineId); const accepted = await acceptHandoff(f.vault, handoff.handoffId, f.b, bSnapshot, f.configB, { now: new Date("2026-07-22T13:00:00Z"), blockingConflicts: 0, placeholderCount: 0 }); expect(accepted.status).toBe("accepted"); await expect(acceptHandoff(f.vault, handoff.handoffId, f.b, bSnapshot, f.configB, { now: new Date("2026-07-22T13:01:00Z") })).rejects.toMatchObject({ code: "HANDOFF_REQUIRED" }); });
  it("bloque mismatch, placeholder/conflit et conserve le mode désactivé", async () => { const f = await fixture(); expect(await assertPortabilityWriteAllowed({ YOUTUBE_LIBRARY_PATH: f.vault })).toEqual({ enabled: false }); await acquireWriterAuthority(f.vault, f.a, f.checkpoint, 30, { force: true, verifiedBackupId: f.backup.backupId, confirmationText: "REPRENDRE" }); await expect(assertPortabilityWriteAllowed(f.envA, { wait: async () => undefined })).resolves.toMatchObject({ enabled: true, machineId: f.a.machineId }); await writeFile(path.join(f.vault, "INDEX.md"), "# Modifié\n"); await expect(assertPortabilityWriteAllowed(f.envA, { wait: async () => undefined })).rejects.toMatchObject({ code: "CHECKPOINT_MISMATCH" }); });
});

