import { AppHeader } from "@/components/app-header";
import { getDiagnosticOverview } from "@/lib/diagnostics/overview";
import Link from "next/link";

export const dynamic = "force-dynamic";

function Badge({ ok, children }: { ok: boolean; children: React.ReactNode }) {
  return <span className={`rounded-full px-3 py-1 text-xs font-bold ${ok ? "bg-emerald-100 text-emerald-900 dark:bg-emerald-950 dark:text-emerald-200" : "bg-amber-100 text-amber-900 dark:bg-amber-950 dark:text-amber-200"}`}>{children}</span>;
}

export default async function DiagnosticsPage() {
  const diagnostic = await getDiagnosticOverview();
  return <div className="min-h-screen bg-slate-50 dark:bg-slate-950"><AppHeader /><main className="mx-auto max-w-6xl px-5 py-10 sm:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold tracking-[0.16em] text-emerald-700 uppercase dark:text-emerald-300">Lecture seule</p><h1 className="mt-2 text-4xl font-bold">Diagnostic local</h1><p className="mt-3 max-w-2xl text-slate-600 dark:text-slate-400">États utiles à une personne, sans chemin absolu, secret ni vérification cloud implicite.</p></div><Badge ok={diagnostic.vault.status === "ready"}>TubeKnowledge {diagnostic.version}</Badge></div><div className="mt-8 grid gap-4 md:grid-cols-2">
    <section className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-bold">Bibliothèque</h2><Badge ok={diagnostic.vault.status === "ready"}>{diagnostic.vault.status}</Badge></div><p className="mt-3 text-sm text-slate-600 dark:text-slate-300">{diagnostic.vault.message}</p><p className="mt-3 text-2xl font-bold">{diagnostic.vault.markdownFiles} <span className="text-sm font-normal text-slate-500">fichiers Markdown</span></p></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold">Portabilité</h2><Badge ok={!diagnostic.portability.enabled || diagnostic.portability.canWrite}>{diagnostic.portability.enabled ? diagnostic.portability.writerLabel : "Mode mono-machine"}</Badge></div><p className="mt-3 text-sm text-slate-700 dark:text-slate-300">{diagnostic.portability.enabled ? diagnostic.portability.writerLabel : "La portabilité entre machines n’est pas activée."}</p><p className="mt-2 text-sm font-medium">{diagnostic.portability.automaticRenewal.label}</p><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-slate-500">Sauvegardes vérifiées</dt><dd className="font-bold">{diagnostic.portability.verifiedBackups}/{diagnostic.portability.backupCount}</dd></div><div><dt className="text-slate-500">Conflits de connaissance</dt><dd className="font-bold">{diagnostic.portability.knowledgeConflicts}</dd></div></dl>{diagnostic.portability.knowledgeConflicts === 0 ? <p className="mt-3 text-sm text-emerald-700 dark:text-emerald-300">Aucun conflit de contenu ne bloque la bibliothèque.</p> : null}{diagnostic.portability.enabled ? <Link href={diagnostic.portability.recommendedAction.href} className="mt-4 inline-flex rounded-lg border border-cyan-400 px-3 py-2 text-sm font-semibold text-cyan-800 dark:text-cyan-200">{diagnostic.portability.recommendedAction.label} →</Link> : null}<details className="mt-4 text-xs text-slate-500"><summary className="cursor-pointer font-semibold">Détail technique</summary><p className="mt-2">État interne : {diagnostic.portability.writerState} · conflits ouverts : {diagnostic.portability.openConflicts} · avertissements techniques : {diagnostic.portability.technicalConflicts}.</p></details><p className="mt-3 text-xs text-slate-500">État local uniquement. Synchronisation cloud non vérifiée.</p></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-bold">Transcription</h2><Badge ok={diagnostic.transcription.status === "available"}>{diagnostic.transcription.status}</Badge></div><p className="mt-3 text-sm text-slate-500">Disponible signifie que les outils sont configurés et exécutables; l’accès réseau réel est indiqué séparément.</p><ul className="mt-4 space-y-3 text-sm">{diagnostic.transcription.items.map((item) => <li key={item.name} className="rounded-lg border border-slate-100 p-3 dark:border-slate-800"><div className="flex justify-between gap-4"><span>{item.name}</span><strong>{item.status}</strong></div><p className="mt-1 text-xs text-slate-500">{item.detail}</p></li>)}</ul></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><h2 className="text-xl font-bold">Analyse</h2><p className="mt-2 text-sm text-slate-500">Mode par défaut : <strong>{diagnostic.analysis.defaultProvider === "manual" ? "manuel, sans réseau" : diagnostic.analysis.defaultProvider}</strong></p><details className="mt-4 text-sm"><summary className="cursor-pointer font-semibold text-slate-500">Modes disponibles</summary><ul className="mt-3 space-y-2">{diagnostic.analysis.providers.map((provider) => <li key={provider.id} className="flex justify-between gap-4"><span>{provider.label}</span><strong>{provider.configured ? "configuré" : "indisponible"}</strong></li>)}</ul></details></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900 md:col-span-2"><h2 className="text-xl font-bold">Runtimes locaux</h2><div className="mt-4 flex flex-wrap gap-8"><p><strong className="text-2xl">{diagnostic.runtimes.acquisitions}</strong><br /><span className="text-sm text-slate-500">acquisitions</span></p><p><strong className="text-2xl">{diagnostic.runtimes.workflows}</strong><br /><span className="text-sm text-slate-500">traitements</span></p></div><p className="mt-4 text-xs text-slate-500">{diagnostic.recentErrors.message}</p></section>
  </div></main></div>;
}
